[workspace]
resolver = "2"
members = [
	"crates/*"
]

[workspace.dependencies]
anyhow = "1.0.86"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
async-trait = "0.1.81"
log = "0.4.17"
parking_lot = "0.12"
bytes = "1.7.1"
dashmap = "6.1"
rand = "0.8.5"